/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#0b3900",
        "error": "#ffb4ab",
        "surface-variant": "#353535",
        "on-secondary": "#462a00",
        "primary-fixed-dim": "#73de4e",
        "secondary-container": "#ffa504",
        "background": "#131313",
        "surface-container": "#202020",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#653e00",
        "on-error": "#690005",
        "secondary-fixed-dim": "#ffb95c",
        "surface-bright": "#393939",
        "surface": "#131313",
        "error-container": "#93000a",
        "outline": "#899480",
        "tertiary-container": "#babbbb",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#684100",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary-fixed": "#e2e2e2",
        "primary-fixed": "#8efc67",
        "surface-container-low": "#1b1b1b",
        "secondary": "#ffcb8d",
        "primary-container": "#67d243",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-primary": "#1e6d00",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#165700",
        "surface-tint": "#73de4e",
        "inverse-on-surface": "#303030",
        "on-surface-variant": "#becab4",
        "surface-container-highest": "#353535",
        "on-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#042100",
        "on-primary-fixed-variant": "#145200",
        "on-tertiary-container": "#494b4b",
        "surface-dim": "#131313",
        "on-tertiary": "#2f3131",
        "secondary-fixed": "#ffddb7",
        "on-background": "#e5e2e1",
        "primary": "#82ef5c",
        "tertiary": "#d6d7d7",
        "outline-variant": "#3f4a39",
        "on-secondary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#454747"
      },
      fontFamily: {
        "headline": ["Newsreader"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
